# @package model

_target_: dflow.models.sit.SiT
name: sit_s_8

# SiT-S/8 Configuration
input_size: ${compute_latent_size:${dataset.image_size}}
patch_size: 8
in_channels: ${compute_in_channels:${dataset.image_size}}
hidden_size: 384
depth: 12
num_heads: 6
mlp_ratio: 4.0
class_dropout_prob: 0.1
num_classes: ${dataset.num_classes}
learn_sigma: true
