# @package model

_target_: dflow.models.sit.SiT
name: sit_l_2

# SiT-L/2 Configuration
input_size: ${compute_latent_size:${dataset.image_size}}
patch_size: 2
in_channels: 4
hidden_size: 1024
depth: 24
num_heads: 16
mlp_ratio: 4.0
class_dropout_prob: 0.1
num_classes: ${dataset.num_classes}
learn_sigma: true
