# @package model

_target_: dflow.models.sit.SiT
name: sit_b_2

# SiT-B/2 Configuration
input_size: 32
patch_size: 2
in_channels: 4
hidden_size: 768
num_heads: 12
mlp_ratio: 4.0
class_dropout_prob: 0.1
num_classes: ${dataset.num_classes}
learn_sigma: true
