# @package model

_target_: dflow.models.sit.SiT
name: sit_s_2

# SiT-S/2 Configuration
input_size: ${compute_latent_size:${dataset.image_size}}
patch_size: 2
in_channels: 4
hidden_size: 384
depth: 12
num_heads: 6
mlp_ratio: 4.0
class_dropout_prob: 0.1
num_classes: ${dataset.num_classes}
learn_sigma: true
