# @package dataset

dataset:
  # Custom Dataset Configuration
  _target_: dflow.datasets.CustomDataset
  data_path: /path/to/your/dataset
  split: train
  # transform:
  #   _target_: torchvision.transforms.Compose
  #   transforms:
  #     - _target_: torchvision.transforms.Resize
  #       size: [256, 256]
  #     - _target_: torchvision.transforms.RandomHorizontalFlip
  #       p: 0.5
  #     - _target_: torchvision.transforms.ToTensor
  #     - _target_: torchvision.transforms.Normalize
  #       mean: [0.5, 0.5, 0.5]
  #       std: [0.5, 0.5, 0.5]

loader:
  # DataLoader configuration
  batch_size: 256
  shuffle: false
  num_workers: 4
  pin_memory: true
  drop_last: true

# Dataset specific settings
num_classes: 1000  # Adjust based on your dataset
image_size: 256
