# @package dataset

dataset:
  # ImageNet Latent Dataset Configuration
  _target_: dflow.datasets.ImageNetLatentDataset
  data_path: /storage/dataset/imagenet_latent
  split: train
  # transform:
  #   _target_: torchvision.transforms.Compose
  #   transforms:
  #     - _target_: torchvision.transforms.ToTensor
  #     - _target_: torchvision.transforms.Normalize
  #       mean: [0.0, 0.0, 0.0, 0.0]  # 4-channel latent space
  #       std: [1.0, 1.0, 1.0, 1.0]

loader:
  # DataLoader configuration
  batch_size: 256
  shuffle: false
  num_workers: 4
  pin_memory: true
  drop_last: true

# Dataset specific settings
num_classes: 1000
image_size: 32  # Latent space size (256/8 = 32)
latent_channels: 4
