# @package dataset

dataset:
  # ImageNet Dataset Configuration
  _target_: torchvision.datasets.ImageNet
  root: /storage/sunil/imagenet
  split: train
  # transform:
  #   _target_: torchvision.transforms.Compose
  #   transforms:
  #     - _target_: torchvision.transforms.Resize
  #       size: [256, 256]
  #     - _target_: torchvision.transforms.RandomHorizontalFlip
  #       p: 0.5
  #     - _target_: torchvision.transforms.ToTensor
  #     - _target_: torchvision.transforms.Normalize
  #       mean: [0.485, 0.456, 0.406]
  #       std: [0.229, 0.224, 0.225]

loader:
  # DataLoader configuration
  batch_size: 256
  shuffle: true
  num_workers: 4
  pin_memory: true
  drop_last: true

# Dataset specific settings
num_classes: 1000
image_size: 256
name: imagenet