# @package sampling

# ODE Sampling Configuration
method: "ode"
num_steps: 100
cfg_scale: 1.0
num_samples: 4
image_size: 256

# Sampling parameters
solver: "euler"  # euler, rk4, dopri5
rtol: 1.0e-5
atol: 1.0e-5

# Output
save_images: true
save_npz: false
output_format: "png"
