# @package sampling

# SDE Sampling Configuration
method: "sde"
num_steps: 100
cfg_scale: 1.0
num_samples: 4
image_size: 256

# SDE parameters
noise_schedule: "linear"  # linear, cosine, sigmoid
sde_type: "vpsde"  # vpsde, vpsde_2, subvpsde

# Output
save_images: true
save_npz: false
output_format: "png"
