# @package _global_

# Base configuration for dFlow
defaults:
  - setup
  - model: sit_b_4
  - dataset: cifar10
  - loss: mse
  - optimizer: adamw
  - scheduler: cosine
  - sampling: ode
  - training: standard
  - transport: linear
  - vae: ema
  - _self_

# Project settings
project_name: dflow
seed: 42
time: ${now:%m%d%H%M}

# Paths for training
output_dir: ./outputs/${time}
checkpoint_dir: ./checkpoints/${time}
log_dir: ./logs

noise: false
block_wise_noise: false
block_wise_noisev2: false