# @package _global_

# Base configuration for dFlow
defaults:
  - setup
  - model: sit_b_2
  - dataset: cifar10
  - loss: mse
  - optimizer: adamw
  - scheduler: cosine
  - sampling: ode
  - _self_

# Project settings
project_name: dflow
seed: 42

# Paths
output_dir: ./outputs
checkpoint_dir: ./checkpoints
log_dir: ./logs

